@host = http://localhost:5166

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMTAyODRkMy1kN2I5LTQ4MTItOTY5ZC0wNWYyZjY3NTMyODQiLCJnaXZlbl9uYW1lIjoiQW1pY2hhaSIsImZhbWlseV9uYW1lIjoiTWFudGluYmFuZCIsImp0aSI6IjdiN2IzZjBiLTIyZTUtNDQwZS05ZTZiLWE4NTYwYjE1ZWFlZiIsImV4cCI6MTY4OTY3NjgzMiwiaXNzIjoiRGlubmVyQ2hpa2VuIiwiYXVkIjoiRGlubmVyQ2hpa2VuIn0.IrQicseEg9T29I4bPLW18RS6To8VW4tzGtkVbw61BoY